name: pandamo
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - click=7.0
  - flask=1.1.1
  - icc_rt=2019.0.0
  - intel-openmp=2019.4
  - itsdangerous=1.1.0
  - jinja2=2.10.3
  - markupsafe=1.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - numpy=1.16.5
  - numpy-base=1.16.5
  - openssl=1.1.1d
  - pandas=0.25.2
  - pip=19.3.1
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.3
  - scipy=1.3.1
  - setuptools=41.4.0
  - six=1.12.0
  - sqlite=3.30.1
  - tabulate=0.8.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - werkzeug=0.16.0
  - wheel=0.33.6
  - wincertstore=0.2
  - xlrd=1.2.0
  - pip:
    - joblib==0.14.0
    - scikit-learn==0.21.3
    - sklearn==0.0
